#define SETBIT(WORD, BITPOS) WORD|=1<<BITPOS
#define CLRBIT(WORD, BITPOS) WORD&=~(1<<BITPOS)
#define CPLBIT(WORD,BITPOS) WORD^=1<<BITPOS
#define READWRITEBIT(WORD, DBIR, SBET) WORD=(((WORD&~(1<<DBIT)|((WORD>>SBIT)&1)<<DBIT)))
#define WRITEBYTE(WORD, BYETSTARTPOS, BYTE) WORD=((WORD&~(255<<BYETSTARTPOS))|(BYTE<<BYETSTARTPOS))
#define READBIT(WORD, BIT)((WORD>>BIT)&1)
#define WRITEBIT(WORD,BITPOS,BIT) WORD=((WORD &~(1<<BITPOS))|(BIT<<BITPOS))
#define BYTESTARTBIT(WORD,BYTESTARTBIT,BYTE) WORD=((WORD&~(255<<BYTESTARTBIT))|(BYTE<<BYTESTARTBIT))
#define WRITENIBBLE(WORD,NIBBLESTARTPOS,NIBBLE) WORD=((WORD&~(15<<NIBBLESTARTPOS))|(NIBBLE<<NIBBLESTARTPOS))
#define READNIBBLE(WORD,NIBBLESTARTPOS) ((WORD>>NIBBLESTARTPOS)&15)

